server:
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: false
  port: 7777


spring:
  datasource:
    username: root
    password: 20177600
    url: jdbc:mysql://47.98.240.31:3307/auto_deal?userSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  rabbitmq:
#    host: 47.98.240.31 # rabbitmq的连接地址
    host: 172.16.190.2
    port: 5672 # rabbitmq的连接端口号
    virtual-host: /mall # rabbitmq的虚拟host
    username: mall # rabbitmq的用户名
    password: mall # rabbitmq的密码
    publisher-confirms: true #如果对异步消息需要回调必须设置为true


#mybatis开启别名
mybatis:
  type-aliases-package: con.edu.lingnan.deal.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.edu.lingnan.deal.mapper : debug
